FROM davidraila/fedora:user

# Common tools and libs for c++ devel
RUN dnf -y update && dnf -y install @'C Development Tools and Libraries' && dnf clean all
RUN dnf -y install wget git cmake autoconf automake cmake gcc clang && dnf clean all

RUN dnf -y install sudo git wget kde-runtime adobe-source-code-pro-fonts liberation-fonts dejavu\*font\* &&\
	dnf clean all
RUN wget -cqO- https://go.microsoft.com/fwlink/?LinkID=760866 -O /tmp/vscode.rpm  &&\
  	dnf -y install /tmp/vscode.rpm && rm -f /tmp/vscode.rpm &&\
	dnf -y clean all

LABEL description="fedora base for c++ development tooling"
