#
# clang binaries in data container
#
FROM centos:6 as build
RUN yum -y install centos-release-scl scl-utils epel-release && yum -y update
RUN yum -y install devtoolset-7 sclo-git25 cmake3 python27 ccache

#RUN echo 'cd /usr/local/src && git clone --depth=1 https://github.com/Z3Prover/z3.git && git clone --depth=1 https://git.llvm.org/git/llvm.git && git clone --depth=1 https://git.llvm.org/git/clang.git llvm/tools/clang && git clone --depth=1 https://git.llvm.org/git/clang-tools-extra.git llvm/tools/clang/tools/extra && git clone --depth=1 https://git.llvm.org/git/compiler-rt.git llvm/projects/compiler-rt && git clone --depth=1 https://git.llvm.org/git/libcxx.git llvm/projects/libcxx && git clone --depth=1 https://git.llvm.org/git/libcxxabi.git llvm/projects/libcxxabi' | scl enable $(scl -l) --

RUN echo 'cd /usr/local/src && git clone --depth=1 https://github.com/llvm/llvm-project.git' | scl enable $(scl -l) --

#RUN echo 'mkdir -p /usr/local/src/build/z3 && cd /usr/local/src/build/z3 && cmake3 -G "Unix Makefiles" ../../z3 -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/clang && make -j$(grep -c ^processor /proc/cpuinfo) all install' | scl enable $(scl -l) --

#RUN echo 'cd /usr/local/src/llvm-project && mkdir build && cd build && cmake3 -DLLVM_ENABLE_PROJECTS=clang\;clang-tools-extra\;compiler-rt\;lld\;lldb\;libunwind\;libcxxabii\;libcxx\;pstl -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/clang ../llvm && make -j$(grep -c ^processor /proc/cpuinfo) all install' | scl enable $(scl -l) --

RUN echo 'cd /usr/local/src/llvm-project && mkdir build && cd build && cmake3 -DLLVM_ENABLE_PROJECTS=clang\;libcxx\;libcxxabi\;libunwind\;clang-tools-extra\; -DLLVM_TARGETS_TO_BUILD=Native -DCMAKE_BUILD_TYPE=Release -DBOOTSTRAP_CMAKE_BUILD_TYPE=Release -DCLANG_ENABLE_BOOTSTRAP=ON -DCLANG_BOOTSTRAP_TARGETS="install-clang;install-clang-resource-headers"-G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/clang ../llvm && make -j$(grep -c ^processor /proc/cpuinfo) all install' | scl enable $(scl -l) --

#
# Data container with only /usr/local/clang
#
##FROM scratch
##VOLUME /usr/local/clang
##COPY --from=build /usr/local/clang /usr/local/clang

#ENTRYPOINT scl enable $(scl -l) exec
#CMD bash
