FROM davidraila/fedora

RUN dnf -y install git wget kde-runtime adobe-source-code-pro-fonts liberation-fonts dejavu\*font\* gcc golang # plasma-breeze oxygen-fonts 
   
#
# wget and install vscode-insiders
#
RUN echo 'wget -cqO- https://go.microsoft.com/fwlink/?LinkID=760866 -O /tmp/vscode.rpm  &&\
  dnf -y install /tmp/vscode.rpm && rm -f /tmp/vscode.rpm' > /usr/local/bin/update-code && chmod 755 /usr/local/bin/update-code && /usr/local/bin/update-code

