FROM fedora

RUN dnf -y install git curl lzip xz

RUN cd /usr/local/src && git clone https://github.com/gcc-mirror/gcc.git --branch gcc-7-branch --single-branch gcc
RUN curl https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz | tar xzf - && mv mpc-1.1.0 /usr/local/src/gcc/mpc
RUN curl https://gmplib.org/download/gmp/gmp-6.1.2.tar.lz | tar --lzip -xf - && mv gmp-6.1.2 /usr/local/src/gcc/gmp
RUN curl http://www.mpfr.org/mpfr-current/mpfr-4.0.1.tar.xz | tar -xJf - && mv mpfr-4.0.1 /usr/local/src/gcc

VOLUME /usr/local/gcc
VOLUME /usr/local/src/gcc
