FROM centos:6

#
# repos
#
RUN \
   yum -y install \
      centos-release-scl \
      scl-utils \
      epel-release \
   && yum -y update

#
# tooling
#
RUN \
   yum -y install \
      devtoolset-8 \
      rh-git29 \
      rh-python36-python \
      rh-python36-python-devel \
      rh-python36-python-pip \
      #python27 \
      #python27-python-devel \
      #python27-python-pip \
      ccache

#
# Useful packages
#
RUN yum -y install \
      wget \
      socat \
      sudo

#
# Globus devel tools and dependencies
#
RUN yum -y install \
   autogen \
   autoconf \
   automake \
   cmake \
   cmake-gui \
   libtool-ltdl-devel \
   libtool \
   autogen-libopts-devel \
   openssl-devel \
   glibc-utils \
   ksh \
   libtirpc-devel \
   libtool-ltdl

# 
# setup scl for bash
#
RUN for i in $(scl -l); do echo "source scl_source enable $i" >> /etc/bashrc; done
SHELL [ "/bin/bash", "-c", "-l" ]

#
# Globus sdk and cli
#
RUN pip install --upgrade pip setuptools
RUN pip install globus-cli globus-sdk

#
# globus install GCS
#
COPY globus_install_gcs /tmp
RUN /tmp/globus_install_gcs

#
# Globus devel packages, the ones that are not broken
#
RUN yum -y install `yum list available globus\*devel\* | grep -v xio-net-manager | grep "^globus" | awk '{print $1}'`

COPY --from=davidraila/clang:centos-6 /usr/local/clang /usr/local/clang
ENV PATH=/usr/local/clang/bin:${PATH}

SHELL [ "/bin/bash" ]
CMD /bin/bash
LABEL maintainer=raila@illinois.edu                                                      
LABEL organization="NCSA SET Group: Storage Enabling Technologies Group, National Center for Supercomputing Applications"                                                         