FROM alpine

RUN apk update
RUN apk add git curl

RUN mkdir /usr/local/src && cd /usr/local/src && git clone https://github.com/gcc-mirror/gcc.git --branch gcc-7-branch --single-branch gcc
RUN cd /usr/local/srv/git && curl https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz | tar xzf -

VOLUME /usr/local/gcc
VOLUME /usr/local/src/gcc
