#
# clang binaries in data container
#
FROM centos:6.9 as build
RUN yum -y install centos-release-scl scl-utils epel-release && yum -y update
RUN yum -y install devtoolset-7 sclo-git25 cmake3 python27
RUN echo 'cd /usr/local/src && git clone --depth=1 https://git.llvm.org/git/llvm.git && git clone --depth=1 https://git.llvm.org/git/clang.git llvm/tools/clang && git clone --depth=1 https://git.llvm.org/git/clang-tools-extra.git llvm/tools/clang/tools/clang-tools-extra && git clone --depth=1 https://git.llvm.org/git/compiler-rt.git llvm/projects/compiler-rt && git clone --depth=1 https://git.llvm.org/git/libcxx.git llvm/projects/libcxx && git clone --depth=1 https://git.llvm.org/git/libcxxabi.git llvm/projects/libcxxabi' | scl enable $(scl -l) --
RUN echo 'mkdir /usr/local/src/build && cd /usr/local/src/build && cmake3 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/clang ../llvm && make -j$(grep -c ^processor /proc/cpuinfo) all install' | scl enable $(scl -l) --

#
# Data container with vol from binaries
#
FROM scratch
COPY --from=build /usr/local/clang /usr/local/clang
ENTRYPOINT scl enable $(scl -l) exec
CMD bash
VOLUME /usr/local/clang