FROM dr/code-insiders

RUN dnf -y install \
# tools \
   autogen \
   autoconf \
   automake \
   cmake \
   cmake-gui \
# dsi deps \ 
   libtool-ltdl-devel \
   python27 \
   libtool \
   autogen-libopts-devel \
   openssl-devel \
   glibc-utils \
   libtirpc-devel \
   libtool-ltdl
