FROM centos:7 as build

#
# dev tools
#
RUN yum -y install centos-release-scl scl-utils epel-release && yum -y update
RUN yum -y install devtoolset-8 rh-git29 ccache

#
# globus deps
#
RUN yum -y install \
   autogen \
   autoconf \
   automake \
   cmake \
   cmake-gui \
   libtool-ltdl-devel \
   python27 \
   libtool \
   autogen-libopts-devel \
   openssl-devel \
   glibc-utils \
   libtirpc-devel \
   libtool-ltdl
   
COPY globus_setup_devel /tmp
RUN /tmp/globus_setup_devel

FROM build
#
# Setup scl in bash
#
RUN for i in $(scl -l); do echo "source scl_source enable $i" >> /etc/bashrc; done
CMD bash
LABEL maintainer=raila@illinois.edu                                                      
LABEL organization="NCSA SET Group: Storage Enabling Technologies Group, National Center for Supercomputing Applications"                                                         
