FROM centos:7 as build

#
# repos etc.
#
RUN yum -y install \
      centos-release-scl \
      scl-utils \
      epel-release \
   && yum -y update

#
# Developer tools
RUN yum -y install \
      devtoolset-8 \
      rh-git29 \
      python27 \
      python27-python-devel \
      python27-python-pip \
      boost148 \
      ccache \
      patch

#
# Useful packages
#
RUN yum -y install \
      wget \
      sudo
 
#
# globus devel tools and depencies
#
RUN yum -y install \
   autogen \
   autoconf \
   automake \
   cmake \
   cmake-gui \
   libtool-ltdl-devel \
   libtool \
   autogen-libopts-devel \
   openssl-devel \
   glibc-utils \
   libtirpc-devel \
   libtool-ltdl

# 
# install scl in bashrc
#
RUN for i in $(scl -l); do echo "source scl_source enable $i" >> /etc/bashrc; done
SHELL [ "bash", "-c", "-l" ]

#
# Globus sdk and cli
#
RUN python -m pip install --upgrade pip setuptools
RUN python -m pip install globus-cli globus-sdk

#
# globus install GCS
#
COPY globus_install_gcs /tmp
RUN /tmp/globus_install_gcs

#
# Globus devel packages, the ones that are not broken
#
RUN yum -y install `yum list available globus\*devel\* | grep -v xio-net-manager | grep "^globus" | awk '{print $1}'`

RUN yum -y clean all

FROM build
#
# install scl in bashrc in destination build
#
RUN for i in $(scl -l); do echo "source scl_source enable $i" >> /etc/bashrc; done
CMD bash
LABEL maintainer=raila@illinois.edu                                                      
LABEL organization="NCSA SET Group: Storage Enabling Technologies Group, National Center for Supercomputing Applications"                                                         
